services:
  db:
    image: postgres:15
    container_name: threads-clone-db
    restart: always
    env_file:
      - .env.development            # loads POSTGRES_* at container runtime
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: threads-clone-redis
    restart: always
    env_file:
      - .env.development
    ports:
      - "6380:6379"
    volumes:
      - redis-db:/data

volumes:
  postgres-data:
  redis-db:
